apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhopp-test-development
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rhopp-test/overlays/development
    repoURL: https://github.com/redhat-appstudio-qe/rhooop-gitops.git
    targetRevision: main
  destination:
    namespace: rhopp-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
