apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhopp-test 
  janus-idp.io/tekton: rhopp-test
  backstage.io/kubernetes-id: rhopp-test
  backstage.io/kubernetes-namespace: rhopp 
  app.kubernetes.io/part-of: rhopp-test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  