apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhopp-test
  janus-idp.io/tekton: rhopp-test
  backstage.io/kubernetes-id: rhopp-test
  backstage.io/kubernetes-namespace: rhopp 
  app.kubernetes.io/part-of: rhopp-test
resources: 
- deployment.yaml
- route.yaml
- service.yaml
